## Evaluate F1 - score or Confusion matrix by using Fine-Tuning ResNet18

In [1]:
import os 
import time
import numpy as np

from sklearn.metrics import f1_score, confusion_matrix, classification_report
from tqdm import tqdm

import torch
import torchvision.transforms as transforms
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader, ConcatDataset

import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

from PIL import Image

## GPU Setting ###
USE_CUDA = torch.cuda.is_available()
DEVICE = torch.device("cuda" if USE_CUDA else "cpu")
print(DEVICE)

cuda


In [5]:
class CUB_CAPTCHA(Dataset):
    def __init__(self, transform, mode='train'):
        self.transform = transform
        self.mode = mode
        base_path = 'CAPTCHA_IMAGES_SPLIT'  # 기본 경로 설정

        if self.mode == 'train':
            folder_path = os.path.join(base_path, 'train')
        elif self.mode == 'valid':
            folder_path = os.path.join(base_path, 'val')

        # 모든 하위 폴더의 파일을 포함
        self.image_paths = []
        self.labels = []

        for class_name in os.listdir(folder_path):
            class_path = os.path.join(folder_path, class_name)
            if os.path.isdir(class_path):
                for img_name in os.listdir(class_path):
                    img_path = os.path.join(class_path, img_name)
                    if os.path.isfile(img_path):  # 파일만 추가
                        self.image_paths.append(img_path)
                        self.labels.append(class_name)  # 클래스명으로 라벨 설정

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        img = Image.open(img_path).convert('RGB')
        img = self.transform(img)

        # 라벨을 클래스 이름에서 추출
        label = self.labels[idx]

        # 문자열 라벨을 숫자로 매핑
        label_map = {  # 클래스 이름을 정수로 매핑
            'motorcycle': 0, 'seaplane': 1, 'boat': 2, 'motorbus': 3,
            'bicycle': 4, 'train': 5, 'truck': 6, 'airplane': 7
        }
        label = label_map[label]

        return img, label


In [4]:
'''import splitfolders
splitfolders.ratio("CAPTCHA_DCGAN", output="CAPTCHA_DCGAN_split", seed=1004, ratio=(0, 1))'''

'import splitfolders\nsplitfolders.ratio("CAPTCHA_DCGAN", output="CAPTCHA_DCGAN_split", seed=1004, ratio=(0, 1))'

In [6]:
import os
from PIL import Image
from torch.utils.data import Dataset

class CUB_CAPTCHA_TEST(Dataset):
    def __init__(self, transform, mode='valid'):
        self.transform = transform
        self.mode = mode
        base_path = 'CAPTCHA_DCGAN_split'  # 기본 경로 설정

        # train과 validation에 따라 폴더 경로 설정
        if self.mode == 'train':
            folder_path = os.path.join(base_path, 'train')
        elif self.mode == 'valid':
            folder_path = os.path.join(base_path, 'val')
        else:
            raise ValueError("mode must be 'train' or 'valid'")

        # 모든 하위 폴더의 파일 경로와 라벨 생성
        self.image_paths = []
        self.labels = []

        # 클래스 이름을 정수로 매핑
        self.label_map = {
            'motorcycle': 0, 'seaplane': 1, 'boat': 2, 'motorbus': 3,
            'bicycle': 4, 'train': 5, 'truck': 6, 'airplane': 7
        }

        for class_name in os.listdir(folder_path):
            class_path = os.path.join(folder_path, class_name)
            if os.path.isdir(class_path) and class_name in self.label_map:  # 유효한 클래스 이름만 포함
                for img_name in os.listdir(class_path):
                    img_path = os.path.join(class_path, img_name)
                    if os.path.isfile(img_path):  # 파일만 추가
                        self.image_paths.append(img_path)
                        self.labels.append(class_name)  # 클래스명으로 라벨 설정

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        img = Image.open(img_path).convert('RGB')
        img = self.transform(img)

        # 라벨을 클래스 이름에서 추출하고 정수로 변환
        label = self.labels[idx]
        label = self.label_map[label]

        return img, label


In [7]:
# 데이터 변환 정의
'''transforms_train = transforms.Compose([
    transforms.Resize((448, 448)),              # 크기 조정
    transforms.RandomRotation(15),              # 무작위 회전
    transforms.RandomResizedCrop(448, scale=(0.8, 1.0)),  # 무작위 크롭
    transforms.RandomHorizontalFlip(p=0.5),     # 좌우 반전
    transforms.ToTensor(),                      # 텐서 변환
])'''

transforms_train = transforms.Compose([
    transforms.Resize((64, 64)),              # 크기 조정
    transforms.ToTensor(),                      # 텐서 변환
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # 픽셀 값을 [-1, 1]로 정규화
])

transforms_val = transforms.Compose([
    transforms.Resize((64, 64)),              # 크기 조정
    transforms.ToTensor(),                      # 텐서 변환
])


In [8]:
BATCH_SIZE = 16

original_train_set = CUB_CAPTCHA(mode='train', transform=transforms_train) 
original_val_set = CUB_CAPTCHA(mode='valid', transform=transforms_train)
CAPTCHA_train_set = ConcatDataset([original_train_set, original_val_set])

val_set = CUB_CAPTCHA_TEST(mode = 'valid', transform = transforms_val)

train_loader = DataLoader(CAPTCHA_train_set, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=True)

print('Num of each dataset:', len(CAPTCHA_train_set), len(val_set))
print("Loaded combined dataloader")

Num of each dataset: 4068 352
Loaded combined dataloader


## Pre - trained ResNet Load

In [9]:
## Model / Optimizer ###
EPOCH = 30
lr = 0.001

model = models.resnet18(weights = "DEFAULT")

### Transfer Learning ###
num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 8)
model.to(DEVICE)

params_to_update = []
for name,param in model.named_parameters():
    if 'fc' in name:
        print(name)
        print(param.requires_grad)
        param.requires_grad = True
        params_to_update.append(param)
    else:
        param.requires_grad = False

print("Created a learning model and optimizer")

fc.weight
True
fc.bias
True
Created a learning model and optimizer


In [10]:
optimizer = optim.Adam(params_to_update, lr = 0.001)

In [11]:
### Train / Evaluation ###
def train(model, train_loader, optimizer, epoch):
    model.train()
    for i, (image,target) in enumerate (train_loader):
        image, target = image.to(DEVICE), target.to(DEVICE)
        output = model(image)
        optimizer.zero_grad()
        train_loss = F.cross_entropy(output, target).to(DEVICE)
        
        train_loss.backward() 
        optimizer.step()
        
        if i % 10 ==0:
            print(f"Train_Epoch : {epoch} [{i}/{len(train_loader)}]\tLoss: {train_loss.item():.6f}")
    
    return train_loss

def evaluate(model, val_loader):
    model.eval()
    eval_loss = 0
    correct = 0
    all_preds = []
    all_targets = []
    
    with torch.no_grad():
        for i, (image, target) in enumerate(val_loader):
            image, target = image.to(DEVICE), target.to(DEVICE)
            output = model(image)

            eval_loss += F.cross_entropy(output, target, reduction='sum').item()
            
            # Predicted labels
            pred = output.argmax(dim=1)  # 각 배치에서 가장 높은 값의 인덱스를 예측
            all_preds.extend(pred.cpu().numpy())  # GPU → CPU
            all_targets.extend(target.cpu().numpy())
            
            correct += pred.eq(target).sum().item()
    
    eval_loss /= len(val_loader.dataset)
    eval_accuracy = 100 * correct / len(val_loader.dataset)
    
    # Calculate F1-score
    f1 = f1_score(all_targets, all_preds, average='weighted')
    
    # Generate Confusion Matrix
    conf_matrix = confusion_matrix(all_targets, all_preds)

    # Extract unique classes from the dataset
    unique_classes = sorted(set(all_targets + all_preds))
    target_names = [f"Class {cls}" for cls in unique_classes]
    
    # Print classification report
    print("\nClassification Report:")
    print(classification_report(all_targets, all_preds, target_names=target_names))
    
    print("\nConfusion Matrix:")
    print(conf_matrix)
    
    return eval_loss, eval_accuracy, f1, conf_matrix



In [12]:
import time
import torch.optim as optim
from tqdm import tqdm
import torch

epochs = 30

def train_model():
    start = time.time()
    best = 0
    
    for epoch in tqdm(range(epochs), desc="Epochs"):
        epoch_start = time.time()
        train_loss = train(model, train_loader, optimizer, epoch)
        epoch_end = time.time()
            
        # 각 에포크에 대한 Computation Time, Memory 사용량 기록
        epoch_time = epoch_end - epoch_start
        
        # Test 결과 기록
        test_loss, test_accuracy, test_f1, conf_matrix = evaluate(model, val_loader)
        
        print(f"[Final] Test Loss: {test_loss:.4f}, Accuracy: {test_accuracy:.4f}%, F1-Score: {test_f1:.4f}")
        
        print("Confusion Matrix:")
        print(conf_matrix)
        
        end = time.time()
        elapsed_time = end - start
        print(f"Elapsed Time: {int(elapsed_time / 3600)}h, {int((elapsed_time % 3600) / 60)}m, {int(elapsed_time % 60)}s")

In [13]:
train_model()

Epochs:   0%|          | 0/30 [00:00<?, ?it/s]

Train_Epoch : 0 [0/255]	Loss: 2.324743
Train_Epoch : 0 [10/255]	Loss: 2.162630
Train_Epoch : 0 [20/255]	Loss: 1.598135
Train_Epoch : 0 [30/255]	Loss: 1.740698
Train_Epoch : 0 [40/255]	Loss: 1.184355
Train_Epoch : 0 [50/255]	Loss: 1.162261
Train_Epoch : 0 [60/255]	Loss: 0.829354
Train_Epoch : 0 [70/255]	Loss: 1.004719
Train_Epoch : 0 [80/255]	Loss: 1.092848
Train_Epoch : 0 [90/255]	Loss: 0.961614
Train_Epoch : 0 [100/255]	Loss: 0.478543
Train_Epoch : 0 [110/255]	Loss: 0.932386
Train_Epoch : 0 [120/255]	Loss: 0.541199
Train_Epoch : 0 [130/255]	Loss: 0.343112
Train_Epoch : 0 [140/255]	Loss: 0.429915
Train_Epoch : 0 [150/255]	Loss: 0.864261
Train_Epoch : 0 [160/255]	Loss: 0.753360
Train_Epoch : 0 [170/255]	Loss: 0.512872
Train_Epoch : 0 [180/255]	Loss: 0.593309
Train_Epoch : 0 [190/255]	Loss: 0.643122
Train_Epoch : 0 [200/255]	Loss: 0.477128
Train_Epoch : 0 [210/255]	Loss: 0.601441
Train_Epoch : 0 [220/255]	Loss: 0.796341
Train_Epoch : 0 [230/255]	Loss: 0.495569
Train_Epoch : 0 [240/255]	L

Epochs:   3%|▎         | 1/30 [00:08<04:10,  8.63s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.93      0.20      0.33        64
     Class 1       0.40      0.44      0.42        32
     Class 2       0.36      0.70      0.47        64
     Class 3       0.86      0.19      0.31        32
     Class 4       0.67      0.69      0.68        32
     Class 5       0.30      0.09      0.14        32
     Class 6       0.49      0.61      0.55        64
     Class 7       0.33      0.50      0.40        32

    accuracy                           0.45       352
   macro avg       0.54      0.43      0.41       352
weighted avg       0.56      0.45      0.42       352


Confusion Matrix:
[[13  5 10  1  8  2 20  5]
 [ 0 14 13  0  0  0  4  1]
 [ 0  4 45  0  0  0  4 11]
 [ 0  1 12  6  1  2  7  3]
 [ 1  0  5  0 22  0  0  4]
 [ 0  2 18  0  0  3  3  6]
 [ 0  3 18  0  1  1 39  2]
 [ 0  6  5  0  1  2  2 16]]
[Final] Test Loss: 1.6756, Accuracy: 44.8864%, F1-Score: 0.4228
Confusion Matrix:
[[13  5

Epochs:   7%|▋         | 2/30 [00:13<02:52,  6.15s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.19      0.32        64
     Class 1       0.40      0.66      0.50        32
     Class 2       0.32      0.64      0.42        64
     Class 3       0.50      0.31      0.38        32
     Class 4       0.63      0.81      0.71        32
     Class 5       0.44      0.22      0.29        32
     Class 6       0.56      0.38      0.45        64
     Class 7       0.36      0.44      0.39        32

    accuracy                           0.44       352
   macro avg       0.53      0.46      0.43       352
weighted avg       0.55      0.44      0.42       352


Confusion Matrix:
[[12  5 15  3 10  3 12  4]
 [ 0 21  9  1  0  0  1  0]
 [ 0  7 41  0  1  1  2 12]
 [ 0  0 14 10  1  3  3  1]
 [ 0  2  4  0 26  0  0  0]
 [ 0  3 17  0  0  7  1  4]
 [ 0  4 22  6  2  2 24  4]
 [ 0 10  7  0  1  0  0 14]]
[Final] Test Loss: 1.7731, Accuracy: 44.0341%, F1-Score: 0.4238
Confusion Matrix:
[[12  5

Epochs:  10%|█         | 3/30 [00:17<02:21,  5.25s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.12      0.22        64
     Class 1       0.38      0.66      0.48        32
     Class 2       0.39      0.62      0.48        64
     Class 3       0.52      0.38      0.44        32
     Class 4       0.66      0.66      0.66        32
     Class 5       0.80      0.12      0.22        32
     Class 6       0.47      0.59      0.53        64
     Class 7       0.33      0.47      0.38        32

    accuracy                           0.45       352
   macro avg       0.57      0.45      0.43       352
weighted avg       0.58      0.45      0.42       352


Confusion Matrix:
[[ 8  7  8  4  8  1 24  4]
 [ 0 21  6  0  0  0  4  1]
 [ 0  8 40  1  0  0  3 12]
 [ 0  1 11 12  1  0  6  1]
 [ 0  2  3  0 21  0  1  5]
 [ 0  5 12  3  0  4  2  6]
 [ 0  2 17  3  2  0 38  2]
 [ 0 10  5  0  0  0  2 15]]
[Final] Test Loss: 1.8363, Accuracy: 45.1705%, F1-Score: 0.4213
Confusion Matrix:
[[ 8  7

Epochs:  13%|█▎        | 4/30 [00:21<02:05,  4.82s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.90      0.14      0.24        64
     Class 1       0.53      0.56      0.55        32
     Class 2       0.37      0.84      0.51        64
     Class 3       0.46      0.41      0.43        32
     Class 4       0.70      0.50      0.58        32
     Class 5       0.50      0.12      0.20        32
     Class 6       0.58      0.45      0.51        64
     Class 7       0.34      0.56      0.42        32

    accuracy                           0.46       352
   macro avg       0.55      0.45      0.43       352
weighted avg       0.57      0.46      0.43       352


Confusion Matrix:
[[ 9  8 15  3  4  1 15  9]
 [ 0 18 10  0  0  0  1  3]
 [ 0  1 54  0  0  0  0  9]
 [ 0  1 12 13  1  1  3  1]
 [ 1  1  7  1 16  1  1  4]
 [ 0  0 18  1  0  4  1  8]
 [ 0  1 22  9  1  1 29  1]
 [ 0  4  8  1  1  0  0 18]]
[Final] Test Loss: 1.8849, Accuracy: 45.7386%, F1-Score: 0.4288
Confusion Matrix:
[[ 9  8

Epochs:  17%|█▋        | 5/30 [00:25<01:54,  4.59s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.93      0.22      0.35        64
     Class 1       0.22      0.75      0.34        32
     Class 2       0.38      0.55      0.45        64
     Class 3       0.60      0.38      0.46        32
     Class 4       0.65      0.62      0.63        32
     Class 5       0.42      0.16      0.23        32
     Class 6       0.52      0.36      0.43        64
     Class 7       0.29      0.28      0.29        32

    accuracy                           0.40       352
   macro avg       0.50      0.41      0.40       352
weighted avg       0.53      0.40      0.40       352


Confusion Matrix:
[[14 17  6  1  6  2 12  6]
 [ 0 24  6  0  0  0  2  0]
 [ 0 20 35  0  0  0  2  7]
 [ 0  4  9 12  1  1  3  2]
 [ 0  6  3  0 20  1  0  2]
 [ 0 10 10  1  0  5  1  5]
 [ 1  8 20  6  3  3 23  0]
 [ 0 19  2  0  1  0  1  9]]
[Final] Test Loss: 1.8830, Accuracy: 40.3409%, F1-Score: 0.4015
Confusion Matrix:
[[14 17

Epochs:  20%|██        | 6/30 [00:29<01:46,  4.43s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.91      0.16      0.27        64
     Class 1       0.57      0.50      0.53        32
     Class 2       0.33      0.75      0.46        64
     Class 3       0.83      0.16      0.26        32
     Class 4       0.70      0.66      0.68        32
     Class 5       0.50      0.09      0.16        32
     Class 6       0.51      0.61      0.56        64
     Class 7       0.33      0.50      0.40        32

    accuracy                           0.45       352
   macro avg       0.59      0.43      0.41       352
weighted avg       0.58      0.45      0.42       352


Confusion Matrix:
[[10  5 12  0  7  0 22  8]
 [ 0 16 14  0  0  0  1  1]
 [ 0  1 48  0  0  0  4 11]
 [ 0  1 15  5  0  2  7  2]
 [ 1  1  6  0 21  1  0  2]
 [ 0  0 20  0  0  3  1  8]
 [ 0  1 21  1  1  0 39  1]
 [ 0  3 10  0  1  0  2 16]]
[Final] Test Loss: 2.0133, Accuracy: 44.8864%, F1-Score: 0.4172
Confusion Matrix:
[[10  5

Epochs:  23%|██▎       | 7/30 [00:33<01:39,  4.34s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.86      0.30      0.44        64
     Class 1       0.34      0.56      0.42        32
     Class 2       0.35      0.69      0.47        64
     Class 3       0.56      0.31      0.40        32
     Class 4       0.70      0.44      0.54        32
     Class 5       0.38      0.09      0.15        32
     Class 6       0.62      0.28      0.39        64
     Class 7       0.23      0.56      0.33        32

    accuracy                           0.41       352
   macro avg       0.51      0.40      0.39       352
weighted avg       0.53      0.41      0.40       352


Confusion Matrix:
[[19 12 10  1  3  3  6 10]
 [ 0 18 10  0  0  0  1  3]
 [ 0  4 44  0  0  0  0 16]
 [ 0  3 13 10  1  0  3  2]
 [ 2  4  4  0 14  1  0  7]
 [ 0  4 13  1  0  3  1 10]
 [ 1  3 22  6  1  1 18 12]
 [ 0  5  8  0  1  0  0 18]]
[Final] Test Loss: 1.9227, Accuracy: 40.9091%, F1-Score: 0.4030
Confusion Matrix:
[[19 12

Epochs:  27%|██▋       | 8/30 [00:38<01:34,  4.28s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.80      0.31      0.45        64
     Class 1       0.29      0.50      0.37        32
     Class 2       0.37      0.72      0.48        64
     Class 3       0.55      0.34      0.42        32
     Class 4       0.81      0.53      0.64        32
     Class 5       0.43      0.09      0.15        32
     Class 6       0.57      0.33      0.42        64
     Class 7       0.30      0.56      0.39        32

    accuracy                           0.43       352
   macro avg       0.51      0.42      0.42       352
weighted avg       0.53      0.43      0.42       352


Confusion Matrix:
[[20 10 12  1  3  1 11  6]
 [ 0 16 11  0  0  0  2  3]
 [ 0  5 46  0  0  0  1 12]
 [ 0  3 12 11  0  2  1  3]
 [ 4  4  5  0 17  0  0  2]
 [ 0  6 11  1  0  3  1 10]
 [ 1  4 22  7  1  1 21  7]
 [ 0  7  7  0  0  0  0 18]]
[Final] Test Loss: 1.8956, Accuracy: 43.1818%, F1-Score: 0.4248
Confusion Matrix:
[[20 10

Epochs:  30%|███       | 9/30 [00:42<01:28,  4.23s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.83      0.08      0.14        64
     Class 1       0.25      0.69      0.36        32
     Class 2       0.41      0.50      0.45        64
     Class 3       0.59      0.31      0.41        32
     Class 4       0.71      0.62      0.67        32
     Class 5       0.56      0.16      0.24        32
     Class 6       0.52      0.47      0.49        64
     Class 7       0.27      0.56      0.37        32

    accuracy                           0.40       352
   macro avg       0.52      0.42      0.39       352
weighted avg       0.54      0.40      0.38       352


Confusion Matrix:
[[ 5 20  5  0  7  3 18  6]
 [ 0 22  5  0  0  0  3  2]
 [ 0 11 32  0  0  0  2 19]
 [ 0  8  7 10  1  1  3  2]
 [ 0  5  3  0 20  0  0  4]
 [ 0  6 12  1  0  5  1  7]
 [ 1  6 13  6  0  0 30  8]
 [ 0 11  2  0  0  0  1 18]]
[Final] Test Loss: 2.1243, Accuracy: 40.3409%, F1-Score: 0.3831
Confusion Matrix:
[[ 5 20

Epochs:  33%|███▎      | 10/30 [00:46<01:23,  4.19s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.89      0.25      0.39        64
     Class 1       0.47      0.47      0.47        32
     Class 2       0.34      0.78      0.48        64
     Class 3       0.53      0.31      0.39        32
     Class 4       0.74      0.72      0.73        32
     Class 5       0.71      0.16      0.26        32
     Class 6       0.50      0.48      0.49        64
     Class 7       0.35      0.41      0.38        32

    accuracy                           0.46       352
   macro avg       0.57      0.45      0.45       352
weighted avg       0.57      0.46      0.45       352


Confusion Matrix:
[[16  7 14  1  6  0 16  4]
 [ 0 15 14  0  0  0  2  1]
 [ 0  1 50  0  0  0  3 10]
 [ 0  1 14 10  0  2  4  1]
 [ 1  1  5  0 23  0  1  1]
 [ 0  3 17  1  0  5  1  5]
 [ 1  1 21  6  2  0 31  2]
 [ 0  3 11  1  0  0  4 13]]
[Final] Test Loss: 1.9488, Accuracy: 46.3068%, F1-Score: 0.4492
Confusion Matrix:
[[16  7

Epochs:  37%|███▋      | 11/30 [00:50<01:19,  4.20s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.23      0.38        64
     Class 1       0.48      0.47      0.48        32
     Class 2       0.29      0.80      0.43        64
     Class 3       0.53      0.28      0.37        32
     Class 4       0.90      0.59      0.72        32
     Class 5       0.32      0.19      0.24        32
     Class 6       0.59      0.30      0.40        64
     Class 7       0.28      0.38      0.32        32

    accuracy                           0.41       352
   macro avg       0.55      0.40      0.41       352
weighted avg       0.57      0.41      0.41       352


Confusion Matrix:
[[15  5 19  0  2  6 10  7]
 [ 0 15 15  0  0  1  0  1]
 [ 0  2 51  0  0  0  0 11]
 [ 0  1 15  9  0  3  2  2]
 [ 0  2  5  0 19  2  0  4]
 [ 0  1 22  0  0  6  1  2]
 [ 0  1 31  8  0  1 19  4]
 [ 0  4 16  0  0  0  0 12]]
[Final] Test Loss: 2.1311, Accuracy: 41.4773%, F1-Score: 0.4113
Confusion Matrix:
[[15  5

Epochs:  40%|████      | 12/30 [00:54<01:15,  4.18s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.95      0.28      0.43        64
     Class 1       0.38      0.59      0.46        32
     Class 2       0.55      0.66      0.60        64
     Class 3       0.44      0.56      0.49        32
     Class 4       0.61      0.84      0.71        32
     Class 5       0.43      0.31      0.36        32
     Class 6       0.61      0.44      0.51        64
     Class 7       0.37      0.59      0.45        32

    accuracy                           0.51       352
   macro avg       0.54      0.54      0.50       352
weighted avg       0.59      0.51      0.51       352


Confusion Matrix:
[[18  9  4  2 10  6 10  5]
 [ 0 19  4  3  1  1  2  2]
 [ 0  5 42  0  0  1  1 15]
 [ 0  1  6 18  3  1  3  0]
 [ 0  1  2  0 27  1  0  1]
 [ 0  5  7  2  0 10  1  7]
 [ 1  3  9 14  3  3 28  3]
 [ 0  7  3  2  0  0  1 19]]
[Final] Test Loss: 1.7646, Accuracy: 51.4205%, F1-Score: 0.5055
Confusion Matrix:
[[18  9

Epochs:  43%|████▎     | 13/30 [00:58<01:10,  4.17s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.14      0.25        64
     Class 1       0.38      0.44      0.41        32
     Class 2       0.35      0.75      0.48        64
     Class 3       0.71      0.38      0.49        32
     Class 4       0.82      0.72      0.77        32
     Class 5       0.50      0.16      0.24        32
     Class 6       0.50      0.55      0.52        64
     Class 7       0.32      0.44      0.37        32

    accuracy                           0.45       352
   macro avg       0.57      0.45      0.44       352
weighted avg       0.58      0.45      0.43       352


Confusion Matrix:
[[ 9  8 14  0  4  3 22  4]
 [ 0 14 14  0  0  0  3  1]
 [ 0  1 48  0  0  0  2 13]
 [ 0  1 12 12  0  1  3  3]
 [ 0  2  5  0 23  0  1  1]
 [ 0  4 14  1  0  5  2  6]
 [ 0  2 19  4  1  1 35  2]
 [ 0  5 11  0  0  0  2 14]]
[Final] Test Loss: 2.1479, Accuracy: 45.4545%, F1-Score: 0.4329
Confusion Matrix:
[[ 9  8

Epochs:  47%|████▋     | 14/30 [01:02<01:06,  4.15s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.90      0.14      0.24        64
     Class 1       0.35      0.53      0.42        32
     Class 2       0.36      0.72      0.48        64
     Class 3       0.46      0.50      0.48        32
     Class 4       0.89      0.53      0.67        32
     Class 5       0.56      0.16      0.24        32
     Class 6       0.55      0.52      0.53        64
     Class 7       0.31      0.41      0.35        32

    accuracy                           0.44       352
   macro avg       0.55      0.44      0.43       352
weighted avg       0.56      0.44      0.42       352


Confusion Matrix:
[[ 9 10 10  5  2  2 19  7]
 [ 0 17 13  0  0  0  1  1]
 [ 0  5 46  0  0  0  2 11]
 [ 0  1 11 16  0  0  3  1]
 [ 1  3  7  1 17  1  0  2]
 [ 0  4 14  2  0  5  2  5]
 [ 0  5 13 10  0  1 33  2]
 [ 0  3 15  1  0  0  0 13]]
[Final] Test Loss: 2.0708, Accuracy: 44.3182%, F1-Score: 0.4244
Confusion Matrix:
[[ 9 10

Epochs:  50%|█████     | 15/30 [01:07<01:02,  4.17s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.93      0.22      0.35        64
     Class 1       0.42      0.56      0.48        32
     Class 2       0.39      0.69      0.50        64
     Class 3       0.62      0.47      0.54        32
     Class 4       0.85      0.69      0.76        32
     Class 5       0.57      0.12      0.21        32
     Class 6       0.50      0.55      0.52        64
     Class 7       0.41      0.69      0.51        32

    accuracy                           0.49       352
   macro avg       0.59      0.50      0.48       352
weighted avg       0.59      0.49      0.48       352


Confusion Matrix:
[[14  7 10  1  3  1 24  4]
 [ 0 18  9  0  0  1  2  2]
 [ 0  4 44  0  0  0  2 14]
 [ 0  1  9 15  0  0  4  3]
 [ 0  2  6  0 22  1  0  1]
 [ 0  3 13  2  0  4  2  8]
 [ 1  5 17  5  1  0 35  0]
 [ 0  3  5  1  0  0  1 22]]
[Final] Test Loss: 1.9725, Accuracy: 49.4318%, F1-Score: 0.4763
Confusion Matrix:
[[14  7

Epochs:  53%|█████▎    | 16/30 [01:11<00:58,  4.16s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.23      0.38        64
     Class 1       0.37      0.50      0.43        32
     Class 2       0.37      0.72      0.49        64
     Class 3       0.50      0.47      0.48        32
     Class 4       0.78      0.66      0.71        32
     Class 5       0.36      0.12      0.19        32
     Class 6       0.64      0.47      0.54        64
     Class 7       0.31      0.53      0.40        32

    accuracy                           0.47       352
   macro avg       0.54      0.46      0.45       352
weighted avg       0.58      0.47      0.46       352


Confusion Matrix:
[[15  8  9  2  5  4 12  9]
 [ 0 16 10  1  0  2  1  2]
 [ 0  4 46  0  0  0  1 13]
 [ 0  2 10 15  0  1  2  2]
 [ 0  4  5  0 21  0  0  2]
 [ 0  4 15  2  0  4  1  6]
 [ 0  1 20 10  0  0 30  3]
 [ 0  4 10  0  1  0  0 17]]
[Final] Test Loss: 1.9388, Accuracy: 46.5909%, F1-Score: 0.4562
Confusion Matrix:
[[15  8

Epochs:  57%|█████▋    | 17/30 [01:15<00:54,  4.15s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.22      0.36        64
     Class 1       0.44      0.50      0.47        32
     Class 2       0.35      0.77      0.48        64
     Class 3       0.37      0.56      0.44        32
     Class 4       0.79      0.72      0.75        32
     Class 5       0.38      0.16      0.22        32
     Class 6       0.57      0.27      0.36        64
     Class 7       0.40      0.53      0.46        32

    accuracy                           0.45       352
   macro avg       0.54      0.46      0.44       352
weighted avg       0.57      0.45      0.43       352


Confusion Matrix:
[[14  4 16  6  5  3 10  6]
 [ 0 16 12  1  0  2  0  1]
 [ 0  5 49  0  0  0  0 10]
 [ 0  1  9 18  1  0  2  1]
 [ 0  0  6  0 23  1  0  2]
 [ 0  3 17  3  0  5  1  3]
 [ 0  3 22 19  0  1 17  2]
 [ 0  4  8  2  0  1  0 17]]
[Final] Test Loss: 2.1340, Accuracy: 45.1705%, F1-Score: 0.4325
Confusion Matrix:
[[14  4

Epochs:  60%|██████    | 18/30 [01:19<00:50,  4.17s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.86      0.19      0.31        64
     Class 1       0.40      0.59      0.48        32
     Class 2       0.44      0.59      0.50        64
     Class 3       0.47      0.50      0.48        32
     Class 4       0.87      0.62      0.73        32
     Class 5       0.67      0.12      0.21        32
     Class 6       0.54      0.47      0.50        64
     Class 7       0.26      0.69      0.38        32

    accuracy                           0.46       352
   macro avg       0.56      0.47      0.45       352
weighted avg       0.58      0.46      0.45       352


Confusion Matrix:
[[12 10  5  4  3  1 17 12]
 [ 0 19  5  1  0  1  3  3]
 [ 0  3 38  1  0  0  2 20]
 [ 0  1  9 16  0  0  2  4]
 [ 1  0  3  0 20  0  0  8]
 [ 0  7  8  2  0  4  1 10]
 [ 1  3 16  8  0  0 30  6]
 [ 0  4  3  2  0  0  1 22]]
[Final] Test Loss: 2.0962, Accuracy: 45.7386%, F1-Score: 0.4456
Confusion Matrix:
[[12 10

Epochs:  63%|██████▎   | 19/30 [01:23<00:45,  4.17s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.83      0.30      0.44        64
     Class 1       0.31      0.59      0.40        32
     Class 2       0.37      0.72      0.49        64
     Class 3       0.62      0.47      0.54        32
     Class 4       0.77      0.62      0.69        32
     Class 5       0.35      0.22      0.27        32
     Class 6       0.66      0.39      0.49        64
     Class 7       0.44      0.47      0.45        32

    accuracy                           0.47       352
   macro avg       0.54      0.47      0.47       352
weighted avg       0.56      0.47      0.47       352


Confusion Matrix:
[[19 11  9  0  6  6  9  4]
 [ 0 19 10  0  0  3  0  0]
 [ 0 10 46  0  0  0  1  7]
 [ 0  2 11 15  0  1  2  1]
 [ 1  4  5  0 20  1  0  1]
 [ 0  7 13  1  0  7  1  3]
 [ 2  4 20  8  0  2 25  3]
 [ 1  5 11  0  0  0  0 15]]
[Final] Test Loss: 1.9984, Accuracy: 47.1591%, F1-Score: 0.4710
Confusion Matrix:
[[19 11

Epochs:  67%|██████▋   | 20/30 [01:27<00:41,  4.16s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.88      0.11      0.19        64
     Class 1       0.45      0.56      0.50        32
     Class 2       0.37      0.88      0.52        64
     Class 3       0.52      0.38      0.44        32
     Class 4       0.77      0.72      0.74        32
     Class 5       1.00      0.09      0.17        32
     Class 6       0.48      0.53      0.50        64
     Class 7       0.48      0.38      0.42        32

    accuracy                           0.47       352
   macro avg       0.62      0.46      0.44       352
weighted avg       0.61      0.47      0.43       352


Confusion Matrix:
[[ 7  9 14  1  6  0 24  3]
 [ 0 18 11  1  0  0  2  0]
 [ 0  3 56  0  0  0  1  4]
 [ 0  0 14 12  0  0  6  0]
 [ 0  1  4  0 23  0  1  3]
 [ 0  5 19  2  0  3  1  2]
 [ 1  2 19  6  1  0 34  1]
 [ 0  2 15  1  0  0  2 12]]
[Final] Test Loss: 2.1790, Accuracy: 46.8750%, F1-Score: 0.4276
Confusion Matrix:
[[ 7  9

Epochs:  70%|███████   | 21/30 [01:31<00:37,  4.14s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.92      0.19      0.31        64
     Class 1       0.36      0.50      0.42        32
     Class 2       0.33      0.84      0.48        64
     Class 3       0.59      0.31      0.41        32
     Class 4       0.81      0.53      0.64        32
     Class 5       0.44      0.12      0.20        32
     Class 6       0.54      0.45      0.49        64
     Class 7       0.41      0.41      0.41        32

    accuracy                           0.44       352
   macro avg       0.55      0.42      0.42       352
weighted avg       0.56      0.44      0.42       352


Confusion Matrix:
[[12  9 16  1  3  2 15  6]
 [ 0 16 13  0  0  0  1  2]
 [ 0  3 54  0  0  0  2  5]
 [ 0  2 15 10  0  1  4  0]
 [ 1  3  7  0 17  1  0  3]
 [ 0  7 16  0  0  4  2  3]
 [ 0  1 26  6  1  1 29  0]
 [ 0  3 15  0  0  0  1 13]]
[Final] Test Loss: 2.3999, Accuracy: 44.0341%, F1-Score: 0.4213
Confusion Matrix:
[[12  9

Epochs:  73%|███████▎  | 22/30 [01:36<00:33,  4.15s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.81      0.39      0.53        64
     Class 1       0.34      0.50      0.41        32
     Class 2       0.37      0.66      0.47        64
     Class 3       0.58      0.44      0.50        32
     Class 4       0.72      0.72      0.72        32
     Class 5       0.33      0.19      0.24        32
     Class 6       0.67      0.48      0.56        64
     Class 7       0.34      0.44      0.38        32

    accuracy                           0.49       352
   macro avg       0.52      0.48      0.48       352
weighted avg       0.55      0.49      0.49       352


Confusion Matrix:
[[25  8  6  0  5  5 11  4]
 [ 0 16 10  1  0  2  2  1]
 [ 0  8 42  0  0  1  1 12]
 [ 1  3 10 14  1  2  0  1]
 [ 3  1  4  0 23  0  0  1]
 [ 0  5 13  2  0  6  1  5]
 [ 1  2 17  6  2  2 31  3]
 [ 1  4 11  1  1  0  0 14]]
[Final] Test Loss: 1.8292, Accuracy: 48.5795%, F1-Score: 0.4888
Confusion Matrix:
[[25  8

Epochs:  77%|███████▋  | 23/30 [01:40<00:28,  4.14s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.95      0.28      0.43        64
     Class 1       0.25      0.59      0.36        32
     Class 2       0.34      0.66      0.45        64
     Class 3       0.56      0.28      0.38        32
     Class 4       0.86      0.59      0.70        32
     Class 5       0.21      0.19      0.20        32
     Class 6       0.64      0.33      0.43        64
     Class 7       0.44      0.47      0.45        32

    accuracy                           0.42       352
   macro avg       0.53      0.42      0.42       352
weighted avg       0.56      0.42      0.43       352


Confusion Matrix:
[[18 12 10  1  3  7  9  4]
 [ 0 19 11  0  0  2  0  0]
 [ 0 10 42  0  0  3  1  8]
 [ 0  7 11  9  0  4  0  1]
 [ 0  5  5  0 19  1  0  2]
 [ 0  8 14  1  0  6  1  2]
 [ 1  5 24  5  0  6 21  2]
 [ 0  9  7  0  0  0  1 15]]
[Final] Test Loss: 2.2139, Accuracy: 42.3295%, F1-Score: 0.4284
Confusion Matrix:
[[18 12

Epochs:  80%|████████  | 24/30 [01:44<00:24,  4.16s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.89      0.27      0.41        64
     Class 1       0.52      0.50      0.51        32
     Class 2       0.33      0.83      0.47        64
     Class 3       0.62      0.31      0.42        32
     Class 4       0.76      0.69      0.72        32
     Class 5       0.36      0.16      0.22        32
     Class 6       0.57      0.42      0.49        64
     Class 7       0.37      0.41      0.39        32

    accuracy                           0.46       352
   macro avg       0.55      0.45      0.45       352
weighted avg       0.57      0.46      0.45       352


Confusion Matrix:
[[17  6 15  1  6  2 12  5]
 [ 0 16 12  0  0  1  2  1]
 [ 0  2 53  0  0  0  1  8]
 [ 0  0 15 10  0  3  3  1]
 [ 1  3  4  0 22  1  0  1]
 [ 0  2 21  0  0  5  1  3]
 [ 1  1 25  4  1  2 27  3]
 [ 0  1 16  1  0  0  1 13]]
[Final] Test Loss: 2.1573, Accuracy: 46.3068%, F1-Score: 0.4533
Confusion Matrix:
[[17  6

Epochs:  83%|████████▎ | 25/30 [01:48<00:20,  4.17s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.23      0.38        64
     Class 1       0.42      0.50      0.46        32
     Class 2       0.34      0.77      0.47        64
     Class 3       0.48      0.41      0.44        32
     Class 4       0.81      0.66      0.72        32
     Class 5       0.33      0.16      0.21        32
     Class 6       0.62      0.44      0.51        64
     Class 7       0.39      0.50      0.44        32

    accuracy                           0.46       352
   macro avg       0.55      0.46      0.45       352
weighted avg       0.58      0.46      0.45       352


Confusion Matrix:
[[15  6 15  4  5  4 11  4]
 [ 0 16 14  0  0  0  1  1]
 [ 0  3 49  0  0  1  1 10]
 [ 0  0 12 13  0  2  3  2]
 [ 0  2  7  1 21  1  0  0]
 [ 0  6 12  2  0  5  1  6]
 [ 0  1 25  6  0  2 28  2]
 [ 0  4 11  1  0  0  0 16]]
[Final] Test Loss: 2.2181, Accuracy: 46.3068%, F1-Score: 0.4544
Confusion Matrix:
[[15  6

Epochs:  87%|████████▋ | 26/30 [01:52<00:16,  4.20s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.33      0.49        64
     Class 1       0.40      0.56      0.47        32
     Class 2       0.31      0.84      0.45        64
     Class 3       0.44      0.34      0.39        32
     Class 4       0.69      0.78      0.74        32
     Class 5       1.00      0.06      0.12        32
     Class 6       0.58      0.23      0.33        64
     Class 7       0.43      0.31      0.36        32

    accuracy                           0.44       352
   macro avg       0.61      0.43      0.42       352
weighted avg       0.61      0.44      0.42       352


Confusion Matrix:
[[21  9 17  1  7  0  6  3]
 [ 0 18 13  0  0  0  1  0]
 [ 0  5 54  0  0  0  1  4]
 [ 0  1 18 11  0  0  2  0]
 [ 0  2  4  0 25  0  0  1]
 [ 0  4 19  2  0  2  1  4]
 [ 0  3 32 10  3  0 15  1]
 [ 0  3 17  1  1  0  0 10]]
[Final] Test Loss: 2.3737, Accuracy: 44.3182%, F1-Score: 0.4211
Confusion Matrix:
[[21  9

Epochs:  90%|█████████ | 27/30 [01:57<00:13,  4.44s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.23      0.38        64
     Class 1       0.32      0.56      0.41        32
     Class 2       0.34      0.80      0.48        64
     Class 3       0.62      0.31      0.42        32
     Class 4       0.95      0.66      0.78        32
     Class 5       0.38      0.09      0.15        32
     Class 6       0.57      0.45      0.50        64
     Class 7       0.41      0.44      0.42        32

    accuracy                           0.46       352
   macro avg       0.57      0.44      0.44       352
weighted avg       0.59      0.46      0.45       352


Confusion Matrix:
[[15 16 12  0  1  1 15  4]
 [ 0 18 12  0  0  0  1  1]
 [ 0  5 51  0  0  0  1  7]
 [ 0  1 18 10  0  0  3  0]
 [ 0  4  4  0 21  1  0  2]
 [ 0  5 18  1  0  3  2  3]
 [ 0  3 22  5  0  2 29  3]
 [ 0  4 13  0  0  1  0 14]]
[Final] Test Loss: 2.3464, Accuracy: 45.7386%, F1-Score: 0.4454
Confusion Matrix:
[[15 16

Epochs:  93%|█████████▎| 28/30 [02:03<00:09,  4.92s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       0.95      0.28      0.43        64
     Class 1       0.22      0.56      0.32        32
     Class 2       0.31      0.72      0.43        64
     Class 3       0.53      0.31      0.39        32
     Class 4       0.80      0.62      0.70        32
     Class 5       0.40      0.12      0.19        32
     Class 6       0.61      0.27      0.37        64
     Class 7       0.50      0.34      0.41        32

    accuracy                           0.41       352
   macro avg       0.54      0.40      0.41       352
weighted avg       0.56      0.41      0.41       352


Confusion Matrix:
[[18 15 14  1  4  1  9  2]
 [ 0 18 14  0  0  0  0  0]
 [ 0 13 46  0  0  1  0  4]
 [ 0  6 14 10  0  1  0  1]
 [ 0  5  5  0 20  0  1  1]
 [ 0  9 14  1  0  4  1  3]
 [ 1  8 27  7  1  3 17  0]
 [ 0  7 14  0  0  0  0 11]]
[Final] Test Loss: 2.4287, Accuracy: 40.9091%, F1-Score: 0.4077
Confusion Matrix:
[[18 15

Epochs:  97%|█████████▋| 29/30 [02:10<00:05,  5.32s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.25      0.40        64
     Class 1       0.28      0.59      0.38        32
     Class 2       0.35      0.66      0.45        64
     Class 3       0.47      0.25      0.33        32
     Class 4       0.80      0.75      0.77        32
     Class 5       0.62      0.16      0.25        32
     Class 6       0.55      0.45      0.50        64
     Class 7       0.41      0.50      0.45        32

    accuracy                           0.45       352
   macro avg       0.56      0.45      0.44       352
weighted avg       0.58      0.45      0.44       352


Confusion Matrix:
[[16 11 11  0  6  1 16  3]
 [ 0 19 10  0  0  0  2  1]
 [ 0 10 42  0  0  0  1 11]
 [ 0  7 11  8  0  2  3  1]
 [ 0  3  4  0 24  0  0  1]
 [ 0  8 11  2  0  5  1  5]
 [ 0  3 25  6  0  0 29  1]
 [ 0  7  7  1  0  0  1 16]]
[Final] Test Loss: 2.2013, Accuracy: 45.1705%, F1-Score: 0.4437
Confusion Matrix:
[[16 11

Epochs: 100%|██████████| 30/30 [02:16<00:00,  4.55s/it]


Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      0.28      0.44        64
     Class 1       0.42      0.53      0.47        32
     Class 2       0.38      0.73      0.50        64
     Class 3       0.43      0.41      0.42        32
     Class 4       0.70      0.81      0.75        32
     Class 5       0.28      0.16      0.20        32
     Class 6       0.65      0.34      0.45        64
     Class 7       0.39      0.62      0.48        32

    accuracy                           0.48       352
   macro avg       0.53      0.49      0.46       352
weighted avg       0.57      0.48      0.46       352


Confusion Matrix:
[[18  7 13  1  9  4  9  3]
 [ 0 17 10  0  0  2  1  2]
 [ 0  2 47  0  1  0  1 13]
 [ 0  0 15 13  0  2  0  2]
 [ 0  2  3  0 26  1  0  0]
 [ 0  7  9  2  0  5  1  8]
 [ 0  3 19 12  1  4 22  3]
 [ 0  2  8  2  0  0  0 20]]
[Final] Test Loss: 2.1836, Accuracy: 47.7273%, F1-Score: 0.4639
Confusion Matrix:
[[18  7